# Transformers backend - full activation access
_target_: cotlab.backends.TransformersBackend

device: cuda
# device: mps
dtype: bfloat16
enable_hooks: true
trust_remote_code: true

# Quantization (optional; requires bitsandbytes)
# load_in_4bit: true
# bnb_4bit_quant_type: nf4
# bnb_4bit_compute_dtype: bfloat16
# bnb_4bit_use_double_quant: true
