# TCGA Dataset
_target_: cotlab.datasets.loaders.TCGADataset
name: tcga

reports_filename: "tcga/TCGA_Reports.csv"
labels_filename: "tcga/tcga_patient_to_cancer_type.csv"
split: test  # train, test, or all
