# Cardiology CHD detection prompt
_target_: cotlab.prompts.CardiologyPromptStrategy

name: cardiology
contrarian: false  # Set to true for skeptical reasoning
output_format: json  # Options: json, toml, yaml, xml, toon, markdown, plain
