# MCQ (Multiple Choice Question) prompt strategy
_target_: cotlab.prompts.mcq.MCQPromptStrategy

name: mcq
few_shot: true
output_format: json
answer_first: false  # Set to true for "answer first, then justify" reasoning
