# Oncology malignancy detection prompt
_target_: cotlab.prompts.OncologyPromptStrategy

name: oncology
contrarian: false  # Set to true for skeptical reasoning
output_format: json  # Options: json, toml, yaml, xml, toon, markdown, plain
