# Radiology pathological fracture detection prompt
_target_: cotlab.prompts.RadiologyPromptStrategy

name: radiology
contrarian: false  # Set to true for skeptical reasoning
few_shot: true  # Set to false to remove examples for ablation studies
answer_first: false  # Set to true for "answer first, then justify" reasoning
output_format: json  # Options: json, toml, yaml, xml, toon, markdown, plain
