# Radiology pathological fracture detection prompt
_target_: cotlab.prompts.RadiologyPromptStrategy

name: radiology
contrarian: false  # Set to true for skeptical reasoning
output_format: json  # Options: json, toml, yaml, xml, toon, markdown, plain
